name: Submit sitemap to IndexNow
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Submit sitemap URLs to IndexNow (GitHub Pages variant)
        uses: jakob-bagterp/index-now-submit-sitemap-gh-pages-action@v1
        with:
          host: theintelligententerprisegroup.com
          api_key_location: https://www.theintelligententerprisegroup.com/15df302b5d55448ba51724a4fceb4a4e.txt
          sitemap_locations: https://www.theintelligententerprisegroup.com/sitemap.xml
